#!/bin/sh

# Get all remote branches and track them
git branch -r | grep -v '\->' | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g" | while read remote; do git branch --track "${remote#origin/}" "$remote"; done

# Fetch all remote branches
git fetch --all

# Pull all remote branches
git pull --all